# Generated by Django 3.2.7 on 2021-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_imgage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
